version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: gac-db
      POSTGRES_PASSWORD: gac2022
      POSTGRES_DB: gac
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: on-failure
    ports: 
      - 8080:8080

